# Site settings
title: Alexander Thiemann
email: mail@athiemann.net
description: >
  (functional) programming and more
baseurl: ""
url: "http://athiemann.net"
twitter_username: agrafix
github_username:  agrafix
linkedin_username: alexander-thiemann

exclude: [vendor, Gemfile, .travis.yml, deploy_rsa.enc, deploy_rsa, Dockerfile]

# Build settings
markdown: kramdown

kramdown:
    input: GFM
