#!/usr/bin/env bash
set -e

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

echo "Rebuilding everything ..."
"$SCRIPT_DIR"/cibuild

echo "Sending it up ..."
rsync -r --delete-after --progress --checksum "$SCRIPT_DIR/../_site/" priv-page:/var/www/athiemann.net

echo "Done!"
